#!/bin/bash

aws s3 cp uva_grounds s3://ds2022-xtm9px/

aws s3 presign --expires-in 604800 s3://ds2022-xtm9px/uva_grounds

https://ds2022-xtm9px.s3.us-east-1.amazonaws.com/uva_grounds?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAXKPUZL66BFPKFFKV%2F20240929%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240929T223456Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8394bdeb1c97a55a46b5c8a976e1cc7614d1b78ac6cb0acbf06f1bbffe4b22d4
