#!usr/bin/env python3
import boto3
import requests

s3 = boto3.client('s3')

bucket = 'ds2022-xtm9px'
local_file = 'project/uva_grounds'

resp = s3.put_object(
  Body = local_file,
  Bucket = bucket,
  Key = local_file
)

bucket_name = 'ds2022-xtm9px'
object_name = 'uva_grounds'
expires_in = 604800

response = s3.generate_presigned_url(
    'get_object',
    Params={'Bucket': bucket_name, 'Key': object_name},
    ExpiresIn=expires_in
)


#Could not output presigned URL
